OWNER_ID: 534828861586800676 # DO NOT SET THIS TO SOMEONE UNTRUSTED!
OWNER_NAME: 'Skekdog'

NAME: 'Skekbot'
DESCRIPTION: 'Skekbot is a Discord bot, developed by... Skekdog, using the [discord.py](https://github.com/Rapptz/discord.py) library.\nClick [here](https://discord.com/api/oauth2/authorize?client_id=1054474727642628136&permissions=311385508864&scope=bot+applications.commands) to invite Skekbot to your server.'
PRIVACY_POLICY: '[Privacy Disclaimer](https://github.com/Skekdog/Skekbot/blob/master/PRIVACY.md)'
SOURCE_CODE: '[GitHub](https://www.github.com/Skekdog/Skekbot)'
COPYRIGHT: 'Copyright Skekdog © 2024'

WEBSOCKET_RECONNECT_INTERVAL: 5


# OWNER_ID   : DO NOT SET THIS TO SOMEONE UNTRUSTED! The Discord ID of the bot owner, used for /execute.
# OWNER_NAME : Name of the bot author, displayed in /about.

# NAME       : Name of the bot itself, displayed in various locations.
# DESCRIPTION: Description of the bot, displayed in /about.
# SOURCE_CODE: A link to the source code.
# COPYRIGHT  : The copyright notice.

# WEBSOCKET_RECONNECT_INTERVAL: Time in seconds before attempting to reconnect to the announcement WebSocket.